# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/apppackio/apppack/version.BuildDate={{ .Date }}
      - -X github.com/apppackio/apppack/version.Version={{ .Version }}
      - -X github.com/apppackio/apppack/version.Commit={{ .ShortCommit }}
      - -X github.com/apppackio/apppack/version.Environment=production
      - -X main.SentryDSN={{ .Env.SENTRY_DSN }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  -
    skip_upload: auto
    tap:
      owner: apppackio
      name: homebrew-apppack
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://apppack.io
    description: CLI for AppPack.io
    license: Apache-2.0
    test: |
      system "#{bin}/apppack version"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^lint:'
      - '^refactor:'
