package cmd

import (
	"context"
	"fmt"
	"strconv"

	"github.com/apppackio/apppack/app"
	"github.com/apppackio/apppack/diagnose"
	"github.com/apppackio/apppack/ui"
	"github.com/logrusorgru/aurora"
	"github.com/spf13/cobra"
)

var diagnoseModel string

// diagnoseCmd represents the diagnose command
var diagnoseCmd = &cobra.Command{
	Use:   "diagnose [<build-number>]",
	Short: "diagnose a failed deployment using Amazon Bedrock",
	Long: `Gather read-only evidence about a failed deployment -- build phases, logs,
ECS events, and task definitions -- and ask a model on Amazon Bedrock to
diagnose the cause.

Everything runs in your own AWS account using your own credentials. Config
variable values are never read. The diagnosis is advice only; nothing is
modified.`,
	Example: "apppack -a my-app diagnose",
	Args:    cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		var buildNumber *int

		if len(args) > 0 {
			n, err := strconv.Atoi(args[0])
			checkErr(err)
			buildNumber = &n
		}

		ui.StartSpinner()

		a, err := app.Init(AppName, UseAWSCredentials, MaxSessionDurationSeconds)
		checkErr(err)

		answer, err := diagnose.Diagnose(context.Background(), a, buildNumber, diagnoseModel)
		checkErr(err)

		ui.Spinner.Stop()

		fmt.Println(answer)
		fmt.Println()
		fmt.Println(aurora.Faint("This diagnosis was generated by a language model and may be wrong."))
	},
}

func init() {
	rootCmd.AddCommand(diagnoseCmd)
	diagnoseCmd.Flags().StringVar(&diagnoseModel, "model", "", "Bedrock model ID to use (defaults to a Claude model)")
	diagnoseCmd.PersistentFlags().StringVarP(&AppName, "app-name", "a", "", "app name (required)")
	_ = diagnoseCmd.MarkPersistentFlagRequired("app-name")
	diagnoseCmd.PersistentFlags().BoolVar(&UseAWSCredentials, "aws-credentials", false, "use AWS credentials instead of AppPack.io federation")
}
