name: Remove old artifacts

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 1 1 * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@62c2fbea931baa7dd4a6b73ea5a799984a818f61 # v1.8.0
      with:
        age: '7 days'
        skip-tags: true
        skip-recent: 5